services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: groceryPassword
      MYSQL_DATABASE: groceryDB
      MYSQL_USER: grocery
      MYSQL_PASSWORD: groceryPassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullstack
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - fullstack
    env_file:
      - ./backend/.env

volumes:
  mysql-data:

networks:
  fullstack:
    external: true